[build]
	functions = ".functions"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"

[[headers]]
  for = "/.well-known/webfinger"
  [headers.values]
    content-type="application/jrd+json; charset=UTF-8"
